[build]
  command = "npm run build"
  publish = "build"
  edge_functions = true

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[functions]
  node_bundler = "esbuild"

[[edge_functions]]
  function = "render"
  path = "/*" 