[build]
  command = "npm run build"
  publish = ".netlify/functions-internal"
  functions = ".netlify/functions-internal"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[functions]
  node_bundler = "esbuild" 