[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

[functions]
  node_bundler = "esbuild" 